// <auto-generated />
using System;
using GraWat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraWat.Migrations
{
    [DbContext(typeof(GraWatContext))]
    [Migration("20260604095106_SeedDummyProducts")]
    partial class SeedDummyProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraWat.Models.Favoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("GraWat.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("GraWat.Models.SiparisKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisKalemleri");
                });

            modelBuilder.Entity("GraWat.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Ad = "Mat Bitişli Kadife Ruj",
                            Fiyat = 249.90m,
                            Kategori = "Makyaj",
                            ResimYolu = "https://picsum.photos/seed/ruj1/400/400",
                            StokAdedi = 100
                        },
                        new
                        {
                            Id = 102,
                            Ad = "Suya Dayanıklı Siyah Maskara",
                            Fiyat = 299.90m,
                            Kategori = "Makyaj",
                            ResimYolu = "https://picsum.photos/seed/maskara2/400/400",
                            StokAdedi = 80
                        },
                        new
                        {
                            Id = 103,
                            Ad = "Aydınlatıcı Etkili Likit Fondöten",
                            Fiyat = 420.00m,
                            Kategori = "Makyaj",
                            ResimYolu = "https://picsum.photos/seed/fondoten3/400/400",
                            StokAdedi = 50
                        },
                        new
                        {
                            Id = 104,
                            Ad = "Nemlendirici Yüz Kremi (Hyalüronik Asit)",
                            Fiyat = 350.00m,
                            Kategori = "Cilt Bakım",
                            ResimYolu = "https://picsum.photos/seed/krem4/400/400",
                            StokAdedi = 120
                        },
                        new
                        {
                            Id = 105,
                            Ad = "C Vitamini Aydınlatıcı Serum",
                            Fiyat = 480.00m,
                            Kategori = "Cilt Bakım",
                            ResimYolu = "https://picsum.photos/seed/serum5/400/400",
                            StokAdedi = 60
                        },
                        new
                        {
                            Id = 106,
                            Ad = "Nazik Arındırıcı Yüz Temizleme Jeli",
                            Fiyat = 189.90m,
                            Kategori = "Cilt Bakım",
                            ResimYolu = "https://picsum.photos/seed/jel6/400/400",
                            StokAdedi = 150
                        },
                        new
                        {
                            Id = 107,
                            Ad = "Odunsu ve Baharatlı Erkek Parfümü",
                            Fiyat = 850.00m,
                            Kategori = "Parfüm/Deodorant",
                            ResimYolu = "https://picsum.photos/seed/parfum7/400/400",
                            StokAdedi = 30
                        },
                        new
                        {
                            Id = 108,
                            Ad = "Çiçeksi ve Meyveli Kadın Parfümü",
                            Fiyat = 890.00m,
                            Kategori = "Parfüm/Deodorant",
                            ResimYolu = "https://picsum.photos/seed/parfum8/400/400",
                            StokAdedi = 40
                        },
                        new
                        {
                            Id = 109,
                            Ad = "Uzun Süre Etkili Ferah Deodorant",
                            Fiyat = 110.00m,
                            Kategori = "Parfüm/Deodorant",
                            ResimYolu = "https://picsum.photos/seed/deodorant9/400/400",
                            StokAdedi = 200
                        });
                });

            modelBuilder.Entity("GraWat.Models.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("GraWat.Models.Favoriler", b =>
                {
                    b.HasOne("GraWat.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("GraWat.Models.SiparisKalemi", b =>
                {
                    b.HasOne("GraWat.Models.Siparis", "Siparis")
                        .WithMany("SiparisKalemleri")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraWat.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("GraWat.Models.Siparis", b =>
                {
                    b.Navigation("SiparisKalemleri");
                });
#pragma warning restore 612, 618
        }
    }
}
